/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotransversal.vistas;

import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import proyectotransversal.Entidades.Alumno;
import proyectotransversal.accesoADatos.AlumnoData;

/**
 *
 * @author Jesica
 */
public class GestionDeAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionDeAlumnos
     */
    public GestionDeAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jlAlumno = new javax.swing.JLabel();
        jLDocumento = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jLFechaNacimiento = new javax.swing.JLabel();
        jDoc = new javax.swing.JTextField();
        jTApe = new javax.swing.JTextField();
        jTNom = new javax.swing.JTextField();
        jRBActivo = new javax.swing.JRadioButton();
        jbNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();

        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setName("Alumnos"); // NOI18N

        jlAlumno.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlAlumno.setText("Alumno");

        jLDocumento.setText("Documento");

        jLApellido.setText("Apellido");

        jLNombre.setText("Nombre");

        jLEstado.setText("Estado");

        jLFechaNacimiento.setText("Fecha de Nacimiento");

        jDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDocActionPerformed(evt);
            }
        });

        jTApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApeActionPerformed(evt);
            }
        });

        jRBActivo.setText("     Activo");
        jRBActivo.setToolTipText("");
        jRBActivo.setEnabled(false);
        jRBActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBActivoActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.setEnabled(false);
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.setEnabled(false);
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jbNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNombre)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDocumento)
                            .addComponent(jLApellido)
                            .addComponent(jLEstado)
                            .addComponent(jLFechaNacimiento))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jRBActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDoc)
                                    .addComponent(jTApe, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTNom)
                                    .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(83, 83, 83)
                .addComponent(jBBuscar)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jBEliminar)
                .addGap(55, 55, 55)
                .addComponent(jBGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlAlumno)
                .addGap(303, 303, 303))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDocumento)
                    .addComponent(jDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellido))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBActivo)
                    .addComponent(jLEstado))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFechaNacimiento)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jBEliminar)
                    .addComponent(jBGuardar)
                    .addComponent(jBSalir))
                .addGap(52, 52, 52))
        );

        getAccessibleContext().setAccessibleName("Alumnos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jDoc.setText("");
        jTApe.setText("");
        jTNom.setText("");
        
        //al borrar mostraba en el jDate la fecha actual.
//        jDate.setDate(Date.valueOf(LocalDate.now()));

        //Al borrar muestra la fecha de nuevo sin valores como al principio.
        jDate.setDate(null);
        
        jRBActivo.setSelected(false);
        jRBActivo.setEnabled(false);
        
        jBEliminar.setEnabled(false);
        
        jbNuevo.setEnabled(false);

    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDocActionPerformed

    private void jTApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApeActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        
        AlumnoData AluD = new AlumnoData();
//        int id = AluD.buscarAlumnoPorDni(Integer.parseInt(jDoc.getText())).getIdAlumno();

        //Instanciamos un alumno y obtenemos el mismo a traves del metodo.
        Alumno alumno = AluD.buscarAlumnoPorDni((Integer.parseInt(jDoc.getText())));
        
        //obtenemos su estado e id.
        boolean estado = alumno.isActivo();
        int id = alumno.getIdAlumno();
        
        try {
            //corroboramos si el alumno ya esta dado de baja o no.
            if(estado == false){
                //Si el alumno ya fue dado de baja lo aclara por pantalla.
                JOptionPane.showMessageDialog(null, "El alumno ya fue dado de baja. (Estado = 0)");
            }else{
                //Si el alumno esta activo lo da de baja.
                AluD.eliminarAlumno(id);
            }

            jDoc.setText("");
            jTApe.setText("");
            jTNom.setText("");
            //setea la fecha para que no muestre ningun dato.
            jDate.setDate(null);   
            
            jRBActivo.setSelected(false);
            jRBActivo.setEnabled(false);
            
            jBEliminar.setEnabled(false);
            
            jbNuevo.setEnabled(false);
            
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Debe buscar la materia a eliminar");
        }
        
        
        
        
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
this.dispose();      
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jRBActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBActivoActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        
         try {
            AlumnoData AluD = new AlumnoData();

            Alumno Alu = AluD.buscarAlumnoPorDni(Integer.parseInt(jDoc.getText())) ;

            jTApe.setText(Alu.getApellido());
            jTNom.setText(Alu.getNombre());
            jDate.setDate(Date.valueOf(Alu.getFechaNac()));    
            
            jRBActivo.setSelected(Alu.isActivo());
            jRBActivo.setEnabled(true);
            
            jBEliminar.setEnabled(true);
            
            jbNuevo.setEnabled(true);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Codigo incorrecto o campo vacio");
            jDoc.setText("");

        } catch (NullPointerException ex) {

            jDoc.setText("");

        }
        
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
          
        AlumnoData AluD = new AlumnoData();
        Alumno alu = new Alumno();

       try{
           alu.setDni(Integer.parseInt(jDoc.getText()));
           alu.setApellido(jTApe.getText());
           alu.setNombre(jTNom.getText());
           alu.setActivo(true);
           alu.setFechaNac(LocalDate.of(jDate.getDate().getYear(), jDate.getDate().getMonth(), jDate.getDate().getDay()));
           
//           Con este metodo conseguimos el ID del alumno para el metodo modificarAlumno.
           alu = AluD.buscarAlumnoPorDni(alu.getDni());
           
//           modificar alumno existente.
            AluD.modificarAlumno(alu);
            
        }catch (NullPointerException d) {
           JOptionPane.showMessageDialog(null, "Agregando alumno.");
           
//           guardar alumno nuevo.
           AluD.guardarAlumno(alu);
        }
        
        jRBActivo.setEnabled(true);
        jRBActivo.setSelected(true);
        
        jBEliminar.setEnabled(true);

        jbNuevo.setEnabled(true);   
    }//GEN-LAST:event_jBGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private com.toedter.calendar.JDateChooser jDate;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JTextField jDoc;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLDocumento;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechaNacimiento;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JRadioButton jRBActivo;
    private javax.swing.JTextField jTApe;
    private javax.swing.JTextField jTNom;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JLabel jlAlumno;
    // End of variables declaration//GEN-END:variables
}
